// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWRPGCombatTracker.Models;

namespace SWRPGCombatTracker.Migrations
{
    [DbContext(typeof(CombatContext))]
    [Migration("20190304025417_removerequiredobligation")]
    partial class removerequiredobligation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("SWRPGCombatTracker.Models.DestinyPointsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Dark");

                    b.Property<int>("Light");

                    b.HasKey("Id");

                    b.ToTable("DestinyPoints");
                });

            modelBuilder.Entity("SWRPGCombatTracker.Models.PlayerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Agility");

                    b.Property<int>("Brawn");

                    b.Property<string>("Career")
                        .IsRequired();

                    b.Property<string>("CharacterName")
                        .IsRequired();

                    b.Property<int>("CriticalInjuries");

                    b.Property<int>("Cunning");

                    b.Property<int>("CurrentStrain");

                    b.Property<int>("CurrentWounds");

                    b.Property<int>("CurrentXP");

                    b.Property<int>("Encumberance");

                    b.Property<int>("Intellect");

                    b.Property<int>("MaxEncumberance");

                    b.Property<int>("MeleeDefense");

                    b.Property<int>("Morality");

                    b.Property<int>("Presence");

                    b.Property<int>("RangedDefense");

                    b.Property<int>("SoakValue");

                    b.Property<string>("Species")
                        .IsRequired();

                    b.Property<int>("StrainThreshold");

                    b.Property<int>("TotalXP");

                    b.Property<int>("Willpower");

                    b.Property<int>("WoundThreshold");

                    b.HasKey("ID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SWRPGCombatTracker.Models.PlayerModel+IndividualObligations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Obligation")
                        .IsRequired();

                    b.Property<int?>("PlayerModelID");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("PlayerModelID");

                    b.ToTable("IndividualObligations");
                });

            modelBuilder.Entity("SWRPGCombatTracker.Models.PlayerModel+PartyObligations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Obligation")
                        .IsRequired();

                    b.Property<int?>("PlayerModelID");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("PlayerModelID");

                    b.ToTable("PartyObligations");
                });

            modelBuilder.Entity("SWRPGCombatTracker.Models.PlayerModel+Specializations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PlayerModelID");

                    b.Property<string>("Specialization")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("PlayerModelID");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("SWRPGCombatTracker.Models.PlayerModel+IndividualObligations", b =>
                {
                    b.HasOne("SWRPGCombatTracker.Models.PlayerModel")
                        .WithMany("individualObligations")
                        .HasForeignKey("PlayerModelID");
                });

            modelBuilder.Entity("SWRPGCombatTracker.Models.PlayerModel+PartyObligations", b =>
                {
                    b.HasOne("SWRPGCombatTracker.Models.PlayerModel")
                        .WithMany("partyObligations")
                        .HasForeignKey("PlayerModelID");
                });

            modelBuilder.Entity("SWRPGCombatTracker.Models.PlayerModel+Specializations", b =>
                {
                    b.HasOne("SWRPGCombatTracker.Models.PlayerModel")
                        .WithMany("Specialization")
                        .HasForeignKey("PlayerModelID");
                });
#pragma warning restore 612, 618
        }
    }
}
